// Firebase configuration for the Bings app (project: bings-828e1).
// Normally generated by `flutterfire configure`. Values below match
// android/app/google-services.json.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      // TODO(web): run `flutterfire configure` and paste the real web values
      // from Firebase console (bings-828e1 > Project settings > Web app).
      // Placeholders below compile but will NOT connect until replaced.
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for iOS - '
          'run flutterfire configure to add iOS support.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFFCTLYjWdgSYOfiEWFm6X2K7vLdNN7lc',
    appId: '1:690198264750:android:e9ae61eabb6a33aa34a63f',
    messagingSenderId: '690198264750',
    projectId: 'bings-828e1',
    storageBucket: 'bings-828e1.firebasestorage.app',
  );

  // TODO(web): replace placeholders with real values from `flutterfire configure`.
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'REPLACE_WITH_WEB_API_KEY',
    appId: 'REPLACE_WITH_WEB_APP_ID',
    messagingSenderId: '690198264750',
    projectId: 'bings-828e1',
    authDomain: 'bings-828e1.firebaseapp.com',
    storageBucket: 'bings-828e1.firebasestorage.app',
  );
}
